import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e4e2de",
        "primary-container": "#ff6b35",
        "inverse-on-surface": "#f2f0ed",
        "on-primary-container": "#5f1900",
        "on-secondary": "#ffffff",
        "surface": "#fbf9f5",
        "on-secondary-container": "#7d1f84",
        "surface-container-high": "#eae8e4",
        "secondary": "#943699",
        "tertiary": "#225ea9",
        "primary-fixed": "#ffdbd0",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#37003c",
        "on-tertiary-fixed-variant": "#00468a",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#a8c8ff",
        "surface-container-low": "#f5f3ef",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#390c00",
        "secondary-fixed": "#ffd6f9",
        "surface-container-lowest": "#ffffff",
        "primary": "#ab3500",
        "inverse-surface": "#30312e",
        "on-tertiary-container": "#003163",
        "on-tertiary-fixed": "#001b3c",
        "outline": "#8d7168",
        "outline-variant": "#e1bfb5",
        "on-background": "#1b1c1a",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#ffb59d",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#832600",
        "secondary-container": "#fe95fe",
        "background": "#fbf9f5",
        "on-secondary-fixed-variant": "#781a7f",
        "surface-dim": "#dbdad6",
        "surface-container-highest": "#e4e2de",
        "inverse-primary": "#ffb59d",
        "tertiary-container": "#669ae9",
        "secondary-fixed-dim": "#ffa9fc",
        "surface-tint": "#ab3500",
        "tertiary-fixed": "#d6e3ff",
        "on-surface-variant": "#594139",
        "surface-bright": "#fbf9f5",
        "on-surface": "#1b1c1a",
        "on-error-container": "#93000a",
        "surface-container": "#efeeea",
        "retro-yellow": "#ffea00",
        "retro-green": "#00e676",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        margin: "32px",
        "border-width-thin": "2px",
        "shadow-offset": "6px",
        unit: "4px",
        "border-width-thick": "4px",
      },
      fontFamily: {
        "data-mono": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "label-caps": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "headline-xl": ["var(--font-bricolage)", "Bricolage Grotesque", "sans-serif"],
        "headline-lg": ["var(--font-bricolage)", "Bricolage Grotesque", "sans-serif"],
        "headline-md": ["var(--font-bricolage)", "Bricolage Grotesque", "sans-serif"],
        "headline-sm": ["var(--font-bricolage)", "Bricolage Grotesque", "sans-serif"],
        "body-md": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "body-lg": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
      },
      boxShadow: {
        brutal: "6px 6px 0px 0px #000000",
        "brutal-lg": "8px 8px 0px 0px #000000",
        "brutal-sm": "4px 4px 0px 0px #000000",
        "brutal-xs": "2px 2px 0px 0px #000000",
        "brutal-sidebar": "6px 0px 0px 0px #000000",
      },
    },
  },
  plugins: [],
};

export default config;
